TACC/WMA-Tapis-Templates

- applications/opensees-mp/opensees-mp-3.5.0/Dockerfile
- applications/opensees-mp/opensees-mp-3.5.0/Readme.MD
- applications/opensees-mp/opensees-mp-3.5.0/Singularity
- applications/opensees-mp/opensees-mp-3.5.0/app.json
- applications/opensees-mp/opensees-mp-3.5.0/makes/Makefile.def
* Add OpenSeesMP container for version 3.5.0
> Add OpenSeesMP version 3.5.0 using Intel MPI (#2)

- applications/opensees-mp/opensees-mp-3.5.0/app.json
- applications/opensees-sp/opensees-sp-3.5.0/Dockerfile
- applications/opensees-sp/opensees-sp-3.5.0/Singularity
- applications/opensees-sp/opensees-sp-3.5.0/app.json
- applications/opensees-sp/opensees-sp-3.5.0/makes/Makefile.def
* A container for OpenSees SP version 3.5.0
* App.json which enables deployment using tapis
* Singularity file to convert Docker image to Singularity.
* Published OpenSeesSP:3.5.0 docker image
Published app on to portals.tapis.io and tested it with a job.
**App. json**:
`user_id = username
app_id='opensees3-sp-singularity-' + user_id
appVersion='0.0.1'
app_def = {
"id": app_id,
"version": appVersion,
"jobType": "BATCH",
"runtime": "SINGULARITY",
"runtimeOptions": ["SINGULARITY_RUN"],
"description": "A reference application for running OpenSees MP in Tapis v3.",
"containerImage": "docker://taccaci/opensees-sp:3.5.0",
"jobAttributes": {
"execSystemExecDir": "${JobWorkingDir}/jobs/${JobUUID}",
"execSystemInputDir": "${JobWorkingDir}/jobs/${JobUUID}",
"execSystemOutputDir": …
> Task WA-24: OpenSees SP version 3.5.0 container

- applications/napari-ls6/Dockerfile
- applications/napari-ls6/app.json
Napari app with interactive session.
> WA-35 Napari App on LS6

- applications/align-swift/README.md
- applications/align-swift/app.json
- applications/align-swift/profile.json
- applications/align-swift/run.sh
* [WA-61](https://jira.tacc.utexas.edu/browse/WA-61)
* This is tapis v3 equivalent of [AlignEM in prod](https://3dem.org/workbench/applications/AlignEM_Swift_Dev-0.0.8u1).
* It uses development_ng branch in https://github.com/mcellteam/swift-ir 
* The app is based off a runner/wrapper script which launches the app outside a container. The script is similar to the tapis v2 version with some adjustments to clean it up.
* App is available here: https://dev.cep.tacc.utexas.edu/workbench/applications/alignem_swiftng_dev
* [App parameter ](https://dev.cep.tacc.utexas.edu/workbench/applications/alignem_swiftng_dev): queue, time, allocation and job name.
* Job submission is successful and connect button is seen
* Align app is opened.
* Hitting enter in the terminal ends the app.
* Will reach out …
> Task/WA-61 AlignEM Swift-IR Dev NG app

- applications/mpm/app.json
- applications/mpm/profile.json
- applications/mpm/tapisjob_app.sh
Job access: https://dev.cep.tacc.utexas.edu/workbench/applications/mpm?appVersion=1.1.0
```
++ inputfile=mpm.json
++ export LD_LIBRARY_PATH=/home1/apps/swr/20.0.5/lib:/opt/apps/intel19/hdf5/1.10.4/x86_64/lib:/home1/apps/intel19/boost/1.84.0/lib:/opt/apps/intel19/python3/3.7.0/lib:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/libfabric/lib:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/release:/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib:/opt/intel/debugger_2020/libipt/intel64/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.1.217/linux/tbb/lib/intel64_lin/gcc4.8:/opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libr …
```
> MPM tapis v3 job on Frontera

- applications/qgis-ls6/app.json
- applications/qgis-ls6/tapisjob_app.sh
[WA-115](https://tacc-main.atlassian.net/browse/WA-115)
App URL: https://dev.cep.tacc.utexas.edu/workbench/applications/qgis-ls6?appVersion=3.30
> WA-115: QGIS LS6

- applications/qgis-ls6/app.json
- applications/qgis-ls6/tapisjob_app.sh
new app URL -> https://dev.cep.tacc.utexas.edu/workbench/applications/qgis-ls6?appVersion=3.34.4
> update app and docker image to 3.34.4

- applications/kalpana/README.md
- applications/kalpana/app.json
- applications/kalpana/profile.json
- applications/kalpana/tapisjob_app.sh
Added the kalpana_1.0.2.zip file to the containerImage path on the system too.
[WA-149](https://tacc-main.atlassian.net/browse/WA-149)
> task/WA-149: Kalpana v3

- initialize_tenant.py
- systems/cloud.data.exec.tg458981.json
- systems/ds-stko-dev.json
- systems/frontera.json
- systems/ls6.json
- systems/maverick2.json
- systems/secure.frontera.json
- systems/stampede3.json
- systems/wma-dcv-01.json
- systems/wma-exec-01.json
1. Add labels for Systems.
2. Add wma-dcv-01 to system list for Design Safe.
1. Load applications in dev.cep. Did not break UI.
> Add labels to indicate UI friendly names for Systems

- applications/opensees-mp/opensees-mp-s3-3.6.0/Readme.MD
- applications/opensees-mp/opensees-mp-s3-3.6.0/app.json
- applications/opensees-mp/opensees-mp-s3-3.6.0/profile.json
- applications/opensees-mp/opensees-mp-s3-3.6.0/tapisjob_app.sh
- applications/opensees-sp/opensees-sp-s3-3.6.0/Readme.MD
- applications/opensees-sp/opensees-sp-s3-3.6.0/app.json
- applications/opensees-sp/opensees-sp-s3-3.6.0/profile.json
- applications/opensees-sp/opensees-sp-s3-3.6.0/tapisjob_app.sh
* Use Stampede3 module for OpenSees/3.6.0
* Add a generic zip runtime to run Open sees mpi app. Uses ibrun in command line.
* exec system is stampede3
[WA-178](https://tacc-main.atlassian.net/browse/WA-178)
1. Run OpenSees MP: https://dev.cep.tacc.utexas.edu/workbench/applications/opensees-mp-s3
2. Run OpenSees SP: https://dev.cep.tacc.utexas.edu/workbench/applications/opensees-sp-s3
1. Job submission page - help text, parameters shown up with correct info.
2. Job runs and finishes.
3. View output files shows the right content. Look for .out files in inputDirectory which indicates output generated.
**OpenSees SP**
Tapis output
```
++ BINARYNAME=OpenSeesSP
++ INPUTSCRIPT=Example.tcl
++ echo 'INPUTSCRIPT is Example.tcl'
INPUTSCRIPT is Example.tcl
++ TCLSCRIPT=Example.tcl
++ echo 'TCLSCRIPT …
```
> OpenSees SP and MP 3.6 for Stampede3

- applications/LS-Dyna-stampede3/app.json
- applications/LS-Dyna-stampede3/profile.json
- applications/LS-Dyna-stampede3/tapisjob_app.sh
- applications/LS-Dyna/app.json
- applications/LS-Dyna/profile.json
- applications/LS-Dyna/tapisjob_app.sh
- applications/ls-pre-post-stampede3/app.json
- applications/ls-pre-post/app.json
- applications/lsprepost-stampede3/app.json
- [WA-150](https://tacc-main.atlassian.net/browse/WA-150)
Total 4 apps:
[LS-DYNA ( Frontera)](https://dev.cep.tacc.utexas.edu/workbench/applications/LS-Dyna) 
[LS-DYNA (Stampede3)](https://dev.cep.tacc.utexas.edu/workbench/applications/LS-Dyna-stampede3)
[LS-PrePost (Frontera)](https://dev.cep.tacc.utexas.edu/workbench/applications/ls-pre-post?appVersion=4.10.3) 
[LS-PrePost (Stampede3)](https://dev.cep.tacc.utexas.edu/workbench/applications/lsprepost-stampede3?appVersion=4.10.6)
> WA-150: DesignSafe Tapis v3: LS-DYNA

- applications/matlab-express/README.md
- applications/matlab-express/app.json
- applications/matlab-express/tapisjob_app.sh
1. App uses license (unix group)
2. App runs on wma-dcv-01
[WA-162](https://tacc-main.atlassian.net/browse/WA-162)
1. Launch Matlab at https://dev.cep.tacc.utexas.edu/workbench/applications/matlab_express
2. Check app page, job status, connect button, app launches on connect
3. Known bugs:  
Title bar is missing 
window resize
created [WA-186](https://tacc-main.atlassian.net/browse/WA-186) to follow up
To quit, type quit in command window.
Artifacts
> MatLab 2022b express on wma-dcv-01

- applications/matlab-batch/app.json
Update MATLAB Batch to DesignSafe prod to match app listing entry
> task/wa-165 Update MATLAB batch app

- systems/designsafe/designsafe.storage.community.json
- systems/designsafe/designsafe.storage.default.json
- systems/designsafe/designsafe.storage.frontera.work.json
- systems/designsafe/designsafe.storage.work.json
To use in select modal, set the portalNames for systems applicable for selection.
> Add portalNames in notes

- applications/matlab-batch/app.json
- applications/matlab-express/app.json
[WA-292](https://tacc-main.atlassian.net/browse/WA-292)
> matlab labels

- applications/visit-stampede3/app.json
- applications/visit-stampede3/profile.json
Created Visit (Stampede3)
Updated the "modulesToLoad" to include:
- "intel/24.0",
- "impi/21.11",
- "visit/3.4.1"
Test link: [https://www.designsafe-ci.org/rw/workspace/visit-stampede3](https://www.designsafe-ci.org/rw/workspace/visit-stampede3)
> Add Visit Stampede3 application configuration and profile files

- applications/setfacl-corral-wmaprtl/JSON.sh
- applications/setfacl-corral-wmaprtl/app.json
- applications/setfacl-corral-wmaprtl/getUID.sh
- applications/setfacl-corral-wmaprtl/tapisjob_app.sh
- applications/setfacl-corral-wmaprtl/tas.env
- systems/cloud.data.exec.wma_prtl.json
* setup cloud.data wma_prtl exec system.
* Use the same app from design safe with system and user name changes.
* Passing role to the setfacl app. Based on the role, the permission bits are adjusted.
[WA-308](https://tacc-main.atlassian.net/browse/WA-308)
> WA-308: setfacl app for wma_prtl user

- applications/mpm-s3/app.json
- applications/mpm-s3/profile.json
- applications/mpm-s3/tapisjob_app.sh
MPM on Stampede3
- MPM on Stampede3 is replacing the previous Frontera version on Design Safe portal
> MPM Stampede 3

- applications/compress-express/app.json
- applications/compress-express/tapisjob_app.sh
- applications/extract-express/app.json
- applications/extract-express/tapisjob_app.sh
* [WA-387](https://tacc-main.atlassian.net/browse/WA-387)
- Created compress and extract app definitions and run scripts which run on cloud.data VM
- Apps deployed on tapis PORTALS tenant, can test at:
- https://dev.cep.tacc.utexas.edu/workbench/applications/compress-express
- https://dev.cep.tacc.utexas.edu/workbench/applications/extract-express
> task/WA-387: Compress + Extract run on cloud.data

- applications/fiji/Dockerfile
- applications/fiji/app.json
- applications/fiji/run.sh
These changes have been tested and reflect the current state of the public Fiji app at https://3dem.org/workbench/applications/jlabyer-fiji?appVersion=2.14.0
> Update Fiji and add ImageJ.cfg

- applications/adcirc-frontera/app.json
- applications/openfoam-stampede3/app.json
- applications/opensees-mp/opensees-mp-s3/app.json
- applications/opensees-s3/app.json
- applications/opensees-sp/opensees-sp-s3/app.json
- applications/padcirc-swan-frontera/app.json
[WA-460](https://tacc-main.atlassian.net/browse/WA-460) shouldn't be merged until we complete [WA-449](https://tacc-main.atlassian.net/browse/WA-449). None of these apps have been updated with these changes yet.
> task/WA-460 - Add reservation field to OpenSees, ADCIRC and OpenFoam

- systems/frontera.json
- systems/stampede3.json
- systems/vista.json
Designsafe queue labels and filters
> Designsafe queue filter
